### PR TITLE
NewChanges

### PR DESCRIPTION
**Pull request by Doubling005**
These are my new changes

### CODE REVIEW

**Review by Pallavi-Vilas-Kawale — APPROVED** [review]
Done right!!

**Review by Praj2495 — APPROVED** [review]

**Review by Doubling005 — COMMENTED** [review]
HO

**Review by Pallavi-Vilas-Kawale — APPROVED** [review]
Hurrry!! Done great job

**Review by Ashwini-Bhamre — APPROVED** [review]
Approved

**Pull request merged**
